twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        access_news: '%access.news%'
        access_carousel: '%access.carousel%'
        access_stream: '%access.stream%'
        access_stream_index: '%access.stream_index%'
        access_team: '%access.team%'
        access_partner: '%access.partner%'
        access_contact: '%access.contact%'
        contact_name: '%contact.name%'
        contact_email: '%contact.name%'
        contact_phone: '%contact.phone%'
        contact_cellphone: '%contact.cellphone%'
        contact_fax: '%contact.fax%'
        contact_address: '%contact.address%'
        contact_zipcode: '%contact.zipcode%'
        contact_city: '%contact.city%'
        contact_address_complement: '%contact.address_complement%'
        doven_email: '%doven.email%'
        theme_dir: '%theme.dir%'
        theme_template: '%theme.template%'
        theme_index: '%theme.index%'
        theme_onepage: '%theme.onepage%'
        website_name: '%website.name%'
        website_short_name: '%website.short_name%'
        website_description: '%website.description%'
        website_email: '%website.email%'
        website_social_twitter: '%website.social.twitter%'
        website_social_facebook: '%website.social.facebook%'
        website_social_youtube: '%website.social.youtube%'
        website_social_twitch: '%website.social.twitch%'
        website_social_steam: '%website.social.steam%'
        website_social_google: '%website.social.google%'
        upload_dir_carousel: 'uploads/carousel'
        upload_dir_news: '%upload_dir.news%'
        upload_dir_partner: '%upload_dir.partner%'
        upload_dir_stream: '%upload_dir.stream%'
        upload_dir_team: '%upload_dir.team%'
        upload_dir_team_member: '%upload_dir.team_member%'
