easy_admin:
    design:
        menu:
            - { label: Contenu }
            - { entity: News, icon: newspaper-o, label: News, access: '%access.news%', default: true }
            - { entity: Carousel, icon: image, label: Carousel, access: '%access.carousel%', params: { sortField: sort } }
            - { entity: Partner, icon: handshake-o, label: Partenaires, access: '%access.partner%' }
            - { entity: Stream, icon: video-camera, label: Streams, access: '%access.stream%' }
            - label: Équipes
              icon: users
              access: '%access.team%'
              children:
                - { entity: Team, label: Équipes, params: { sortField: sort } }
                - { entity: TeamMember, label: Membres, params: { sortField: team } }
            - { label: Administration }
            - { entity: User, icon: user-circle, label: Admins }
            - { label: Contacter Doven, icon: life-ring, url: 'mailto:%doven.email%?subject=[%website.name%] Contact' }