easy_admin:
    entities:
        Stream:
            class: App\Entity\Stream
            list:
                fields:
                    - id
                    - enabled
                    - main
                    - name
                    - title
                    - game
                    - streamName
                    - { property: image, type: image, base_path: '%upload_dir.stream%' }
                    - twitch
            form:
                fields:
                    - name
                    - title
                    - game
                    - streamName
                    - { property: imageFile, type: vich_image }
                    - twitch