easy_admin:
    entities:
        TeamMember:
            class: App\Entity\TeamMember
            list:
                fields:
                    - id
                    - enabled
                    - name
                    - position
                    - { property: image, type: image, base_path: '%upload_dir.team_member%' }
                    - twitter
                    - facebook
                    - team
                    - sort
            form:
                fields:
                    - name
                    - position
                    - { property: imageFile, type: vich_image }
                    - description
                    - twitter
                    - facebook
                    - team
                    - sort