easy_admin:
    entities:
        Team:
            class: App\Entity\Team
            list:
                fields:
                    - id
                    - enabled
                    - name
                    - game
                    - { property: image, type: image, base_path: '%upload_dir.team%' }
                    - members
                    - sort
            form:
                fields:
                    - name
                    - game
                    - { property: imageFile, type: vich_image }
                    - description
                    - members
                    - sort